name: Issue Create Work Flow

on:
  schedule:
    - cron: '0 0-23/20 * * *'
  workflow_run:
    workflows: [ IssueCreateWorkFlow, codeql, gitguardian ]
    branches: [ development ]
    types: [ completed ]

jobs:
  scanning:
    name: Issue Create Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
          
    - name: Workflow Run Wait
      uses: ahmadnassri/action-workflow-run-wait@v1.4.2
      with:
          github-token: ${{ github.token }}
          timeout: 50000
          delay: 5000
          sha: ${{ github.sha }}
      
    - name: Create Issue Action      
      uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }}
      with:
            title: Build Failed
            token: ${{secrets.GITHUB_TOKEN}}
            labels: worflow-failed
            body: Workflow failed for commit ${{github.sha}}
