name: GitGuardian scan

on: [push, pull_request]

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
          
    - name: Create Issue Action      
      uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }}
      with:
            title: Build Failed
            token: ${{secrets.GITHUB_TOKEN}}
            labels: worflow-failed
            body: Workflow failed for commit ${{github.sha}}
